export declare const openBluetoothAdapter: (option?: WechatMiniprogram.OpenBluetoothAdapterOption | undefined) => void;
export declare const closeBluetoothAdapter: ((option?: WechatMiniprogram.CloseBluetoothAdapterOption | undefined) => void) | undefined;
export declare const getBluetoothAdapterState: (option?: WechatMiniprogram.GetBluetoothAdapterStateOption | undefined) => void;
export declare const onBLECharacteristicValueChange: (listener: WechatMiniprogram.OnBLECharacteristicValueChangeCallback) => void;
export declare const offBLECharacteristicValueChange: (listener?: WechatMiniprogram.OffBLECharacteristicValueChangeCallback | undefined) => void;
export declare const onBluetoothAdapterStateChange: (listener: WechatMiniprogram.OnBluetoothAdapterStateChangeCallback) => void;
export declare const offBluetoothAdapterStateChange: (listener?: WechatMiniprogram.OffBluetoothAdapterStateChangeCallback | undefined) => void;
export declare const onBluetoothDeviceFound: (listener: WechatMiniprogram.OnBluetoothDeviceFoundCallback) => void;
export declare const offBluetoothDeviceFound: (listener: WechatMiniprogram.OnBluetoothDeviceFoundCallback) => void;
export declare const onBLEConnectionStateChange: (listener: WechatMiniprogram.OnBLEConnectionStateChangeCallback) => void;
export declare const offBLEConnectionStateChange: (listener?: WechatMiniprogram.OffBLEConnectionStateChangeCallback | undefined) => void;
export declare const createBLEConnection: (option: WechatMiniprogram.CreateBLEConnectionOption) => void;
export declare const closeBLEConnection: (option: WechatMiniprogram.CloseBLEConnectionOption) => void;
export declare const getConnectedBluetoothDevices: (option: WechatMiniprogram.GetConnectedBluetoothDevicesOption) => void;
export declare const startBluetoothDevicesDiscovery: (option: WechatMiniprogram.StartBluetoothDevicesDiscoveryOption) => void;
export declare const stopBluetoothDevicesDiscovery: (option?: WechatMiniprogram.StopBluetoothDevicesDiscoveryOption | undefined) => void;
export declare const getBLEDeviceCharacteristics: (option: WechatMiniprogram.GetBLEDeviceCharacteristicsOption) => void;
export declare const getBLEDeviceServices: (option: WechatMiniprogram.GetBLEDeviceServicesOption) => void;
export declare const writeBLECharacteristicValue: (option: WechatMiniprogram.WriteBLECharacteristicValueOption) => void;
export declare const notifyBLECharacteristicValueChange: (option: WechatMiniprogram.NotifyBLECharacteristicValueChangeOption) => void;
export declare const readBLECharacteristicValue: (option: WechatMiniprogram.ReadBLECharacteristicValueOption) => void;
export declare const setBLEMTU: (option: WechatMiniprogram.SetBLEMTUOption) => void;
export declare const getSystemInfoSync: () => WechatMiniprogram.SystemInfo;
export declare const getStorage: <T = any, U extends WechatMiniprogram.GetStorageOption<T> = WechatMiniprogram.GetStorageOption<T>>(option: U) => WechatMiniprogram.PromisifySuccessResult<U, WechatMiniprogram.GetStorageOption<T>>;
export declare const setStorage: <T = any, U extends WechatMiniprogram.SetStorageOption<T> = WechatMiniprogram.SetStorageOption<T>>(option: U) => WechatMiniprogram.PromisifySuccessResult<U, WechatMiniprogram.SetStorageOption<T>>;
export declare const removeStorage: <T extends WechatMiniprogram.RemoveStorageOption = WechatMiniprogram.RemoveStorageOption>(option: T) => WechatMiniprogram.PromisifySuccessResult<T, WechatMiniprogram.RemoveStorageOption>;
